### PR TITLE
Feature/multi v alue arguments

### PR DESCRIPTION
**Pull request by b3b00**
the idea of this PR is to allow multiple value for a same argument. Every value is an "instance" of the argument as :
example.exe -arg 1 -arg 2
the mapping property must be a generic List (List<?>), could possibly extended to array.

[CommandLine.Argument('a', "arg")]
private static List MultiArg { get; set; }

### CODE REVIEW

**Comment by b3b00** [comment]
please could you review my PR despite code coverage lowering ? I don't see where covergare lowered in codecov report

**Comment by jpdillingham** [comment]
Thanks for your contribution!  

After taking a look at the code I'm not sure I agree with the introduction of the ```ArgumentValue``` class; I think the use case for repeated arguments would come about far too seldom to justify forcing all other values to use ```.SingleValue```.

As an alternative I'm thinking a less intrusive way to implement this would be to switch the value type of the argument dictionary to ```object```, and when the second instance of the argument is added, convert the object to an array.  The cast within Populate() should sort it out as long as the target property is an array/list.

I'll take a look at adding this over the next few days, or you can take a crack if you're up for it.

**Comment by jpdillingham** [comment]
I incorporated this functionality in PR #14.  I still have some work to do handling the case where multiple arguments are specified for a property backed by an atomic value, and I need to figure out how to prevent previous values from being overwritten if multiple values are supplied using both the short and long argument names.

Please take a look and see if this meets your needs.

**Comment by b3b00** [comment]
thanks for your review. I agree that the use of an ArgumentValue is not the best solution as it breaks the API. The reason is that I allways prefer strongly typed objects rather than "simple object". I 'm ok with your proposal. i have no time for it right now, too busy at work. I will check your work and take the  point if you didnot in next days when i will have more time

**Pull request closed without merging**
